name: flutter


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: self-hosted

    steps:
          
      - uses: actions/checkout@v2
    
    
      - name: Stop main container
        run: | 
          docker stop flutter-web


      - name: Delete the container
        run: |
          docker rm flutter-web
          
          
#       - name: Build an image
#         run: |
#           docker build -t flutter-web .
      
      
      - name: Run the container
        run: |
          docker run -d -p 80:80 --name flutter-web flutter-web
